### ISSUE TITLE
Linux fixes and crash info

### ISSUE THREAD

**Issue by therealfumbles** [OTODESK4193/Ambience#5]
Thanks to OTODESK-san for these amazing plugins. Over time, I've built a few of them here on Linux. This one needed more work than usual to get going so I wanted to share my findings here.

1) First off, build with JUCE 8.0.12. Nothing newer.

2) To fix compilation errors, add these lines to the top of the CMakeLists.txt file, under the project section:

```
add_compile_options(
    $<$<COMPILE_LANG_AND_ID:CXX,GNU,Clang>:-mavx2>
    $<$<COMPILE_LANG_AND_ID:CXX,GNU,Clang>:-mfma>
)

add_compile_definitions(JUCE_WEB_BROWSER=0 JUCE_USE_CURL=0)
```
(For building on Linux it's easier to just set these globally instead of individually for each target).

3) The title headers for the different sections ("Glassmorphic Cards" in the code) truncate the titles on Linux.

In PluginEditor.cpp change the line:
`const float textW = badgeFont.getStringWidthFloat(title) + 16.0f;`
to
`const float textW = juce::GlyphArrangement::getStringWidthInt(badgeFont, title) + 16.0f;`

4) Now for the crash: all of the Plate and Goldfoil presets will crash Ambience. I was able to fix this with the following three sed commands ran from the Source folder:

```
sed -i 's/_mm256_load_ps(/_mm256_loadu_ps(/g' DSP/*.cpp DSP/*.h
sed -i 's/_mm256_store_ps(/_mm256_storeu_ps(/g' DSP/*.cpp DSP/*.h
sed -i 's/_mm256_load_si256(/_mm256_loadu_si256(/g' DSP/*.cpp DSP/*.h
```

--------------

Here's a detailed description of the crash and fix from the LLM that helped me with all this:

Title: Linux builds crash with SIGSEGV due to aligned SIMD loads/stores on misaligned struct members

Summary

Both the standalone build and the VST3 plugin crash with SIGSEGV on Linux when using certain engine modes. The cause is SIMD code that uses aligned loads/stores (_mm256_load_ps, _mm256_store_ps, _mm256_load_si256) on DSP state arrays that are not guaranteed to be 32-byte aligned on Linux builds. The same code runs fine on Windows/MSVC, where struct layout happens to place those members on aligned offsets — but GCC's struct layout on Linux can leave them misaligned, and the aligned instruction variants (vmovaps/vmovaps equivalents) then fault.

Environment

    OS: [debian sid]
    Compiler: GCC 16.2.0 (Debian 16.2.0-2)
    Build: CMake, -DCMAKE_BUILD_TYPE=Release (also reproduces in a debug build with symbols)
    Architecture: x86_64, CPU with AVX2/FMA support
    Affected modes: [Plate and Goldfoil]

Steps to reproduce

    Build from source on Linux with AVX2 enabled.
    Load the VST3 into a host, or run the standalone.
    Switch to one of the affected modes.
    Plugin crashes with SIGSEGV.

Diagnosis

Running the standalone under gdb with debug symbols, the crash occurs in SDNTopology2DMesh::processOneSample (Source/DSP/SDNTopology2DMesh.h:183):
```
Thread 13 "Ambience2.0.1" received signal SIGSEGV, Segmentation fault.
=> vmovaps -0x9c(%rax),%ymm8
```

The effective address is not 32-byte aligned (offset 0x9c from the base), and vmovaps requires 32-byte alignment. This indicates the aligned-load/store intrinsics in the DSP code are operating on struct member arrays whose alignment is not guaranteed on Linux/GCC — struct layout is implementation-defined and differs from MSVC's, which is why the Windows build doesn't crash.

After converting the aligned loads to unaligned variants, the crash moved to the corresponding aligned store, confirming the same root cause across the codebase.

Fix applied locally

Replacing all aligned SIMD memory accesses with their unaligned counterparts resolves the crash. The affected files and intrinsics:

    Source/DSP/EarlyReflectionsISM.cpp: _mm256_load_ps, _mm256_store_ps, _mm256_load_si256
    Source/DSP/SDNTopology2DMesh.h: _mm256_load_ps, _mm256_store_ps
    Source/DSP/SDNTopologySpring1D.h: _mm256_load_ps, _mm256_store_ps
    Source/DSP/SDNTopologyInchindown.h: _mm256_load_ps, _mm256_store_ps
    Source/DSP/SDNEngine.h: _mm256_load_ps, _mm256_store_ps

Concretely:

    _mm256_load_ps → _mm256_loadu_ps
    _mm256_store_ps → _mm256_storeu_ps
    _mm256_load_si256 → _mm256_loadu_si256

On modern x86 CPUs, the unaligned variants have effectively zero performance penalty when the data happens to be aligned, so this is safe even for the Windows builds.

Alternative fixes

Instead of (or in addition to) the unaligned variants, the state arrays could be explicitly aligned using portable alignas(32) declarations and consistent 32-byte-aligned indexing offsets — this would preserve any intentional alignment-based optimizations. However, the unaligned-variant approach is simpler, portable, and removes the entire class of bugs.

Verified: with these changes, both the standalone and VST3 plugin run all modes without crashing on Linux.
